<?php
namespace Netresearch\Composer\Patches;

/*                                                                        *
 * This script belongs to the Composer-TYPO3-Installer package            *
 * (c) 2014 Netresearch GmbH & Co. KG                                     *
 * This copyright notice MUST APPEAR in all copies of the script!         *
 *                                                                        *
 * It is free software; you can redistribute it and/or modify it under    *
 * the terms of the GNU Lesser General Public License, either version 3   *
 * of the License, or (at your option) any later version.                 *
 *                                                                        *
 * The TYPO3 project - inspiring people to share!                         *
 *                                                                        */
use Composer\Installer\MetapackageInstaller;
use Composer\Package\PackageInterface;
use Composer\Repository\InstalledRepositoryInterface;

/**
 * This is just a noop installer to enable packages of type "patches"
 * The patch application is done in the plugin and is not limited to
 * "patches"-packages: Every package that has patches in it's extras
 * is respected there.
 *
 * @deprecated Use package type 'metapackage' instead
 * @author Christian Opitz <christian.opitz at netresearch.de>
 */
class Installer extends MetapackageInstaller {
	/**
	 * @var \Composer\IO\IOInterface
	 */
	protected $io;

	function __construct(\Composer\IO\IOInterface $io)
	{
		$this->io = $io;
	}

	/**
	 * Supports packages of type "patches"
	 * 
	 * @param string $packageType
	 * @return boolean
	 */
	public function supports($packageType) {
		return $packageType == 'patches';
	}

	protected function handleDeprecatedType(PackageInterface $package)
	{
		$this->io->write(
			"<warning>Package type 'patches' is deprecated ({$package}):</warning>"
			. " Use 'metapackage' instead."
		);
		if (method_exists($package, 'setType')) {
			$package->setType('metapackage');
		}
	}

	public function isInstalled(InstalledRepositoryInterface $repo, PackageInterface $package)
	{
		$this->handleDeprecatedType($package);
		return parent::isInstalled($repo, $package);
	}

	public function install(InstalledRepositoryInterface $repo, PackageInterface $package)
	{
		$this->handleDeprecatedType($package);
		parent::install($repo, $package);
	}

	public function update(InstalledRepositoryInterface $repo, PackageInterface $initial, PackageInterface $target)
	{
		$this->handleDeprecatedType($target);
		parent::update($repo, $initial, $target); // TODO: Change the autogenerated stub
	}
}
